---
- name: Domain Join
  hosts: all
  become: yes
  vars_prompt:
    - name: "bind_password"
      prompt: "Password for the AD user"
      private: yes
  tasks:
    - name: Join domain
      command: /bin/bash -c "echo {{ bind_password }} | realm -v join corp.jetstar.com --user=svc_LinuxADInt --computer-ou='OU=Linux,OU=Servers,DC=corp,DC=jetstar,DC=com'"
